# Message broker settings (eg. RabbitMQ)
msg_broker:
  host: localhost
  port: 5672
  virtual_host: /
  username: guest
  password: guest

# Number of worker processes
# WARNING: If changing number of worker processes, the following process must be followed:
# 1. stop all inputs writing to task queue (e.g. httpd, updater)
# 2. when all queues are empty, stop all workers
# 3. reconfigure queues in RabbitMQ using dp3/scripts/rmq_reconfigure.sh
# 4. change the settings here and in /etc/{{DP3_APP}}/supervisor.conf.d/workers.ini
# 5. reload supervisord and start all inputs again
worker_processes: 1

# Number of worker threads per process.
# This may be higher than number of CPUs, because this is not primarily intended
# to utilize computational power of multiple CPUs (which Python cannot do well
# anyway due to the GIL), but to mask long I/O operations (e.g. queries to
# external services via network)
worker_threads: 16

# Path to directory with plug-in modules
# (Relative path is evaluated relative to location of this configuration file)
modules_dir: "../modules"

# List of plug-in modules which should be enabled in processing pipeline. Name of module filename without '.py'
# extension must be used!
enabled_modules:
  - "test_module"
