# Configuration of SnapShooter module, responsible for
# creating entity snapshots and running configured data correlation

# Creating snapshots - period in minutes for creating new snapshots
creation_rate:
  minute: "*/30"
