version: "3.4"

services:
  rabbitmq:
    build: "docker/rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      DP3_APP_NAME: test
      DP3_WORKER_NUM: 1

  postgres:
    build: "docker/postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: test

  redis:
    image: redis
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]

  receiver_api:
    build:
      context: .
      dockerfile: "docker/python/Dockerfile"
      target: "base"
    ports:
      - "5000:5000"
    environment:
      HOST: "0.0.0.0"
    command: [ "python", "api/receiver.py", "test", "./tests/test_config" ]

  worker:
    build:
      context: .
      dockerfile: "docker/python/Dockerfile"
      target: "base"
    command: [ "bin/worker", "test", "./tests/test_config", "0", "-v" ]
    depends_on:
      - rabbitmq
      - postgres

  api_tests:
    build:
      context: .
      dockerfile: "docker/python/Dockerfile"
      target: "base"
    environment:
      BASE_URL: "http://receiver_api:5000/"
    command: [ "python", "-m", "unittest",  "api/tests/test_probability.py" ]

  api_tests2:
    build:
      context: .
      dockerfile: "docker/python/Dockerfile"
      target: "base"
    command: [ "python", "api/tests/test_api.py",  "http://receiver_api:5000/", "2" ]

  unit_tests:
    build:
      context: .
      dockerfile: "docker/python/Dockerfile"
      target: "base"
    command: [ "python", "-m", "unittest",  "tests/test_common/test_config.py" ]