[tool.ruff]
target-version = "py39"

extend-exclude = ["install", "docker"]
line-length = 120
show-fixes = true

select = [
    "I",  # isort
    "UP", # PyUpgrade
    "F",  # Pyflakes
    "E",  # Pycodestyle Errors
    "W",  # Pycodestyle Warnings
    "B",  # Flake8 Bugbear
    "SIM",# Flake8 Simplify
    "C4", # Flake8 Comprehensions
]