[project]
name = "dp3"
version = "0.2.0"
authors = [
    { name = "Vaclav Bartos" },
    { email = "bartos@cesnet.cz" },
]
description = "Dynamic Profile Processing Platform"
readme = "README.md"
license = { file = "LICENSE" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Development Status :: 3 - Alpha",
]
requires-python = ">=3.9"
dynamic = ["dependencies"]

[project.scripts]
worker = "bin.worker:main"
updater = "bin.updater:main"
update_all = "bin.update_all:main"

[project.urls]
Homepage = "https://github.com/CESNET/dp3"
Repository = "https://github.com/CESNET/dp3"
Documentation = "https://cesnet.github.io/dp3"

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }

[tool.setuptools.packages]
find = {}

### Ruff Code Linting ##################################################################
[tool.ruff]
target-version = "py39"

extend-exclude = ["install", "docker"]
line-length = 120
show-fixes = true

select = [
    "I",  # isort
    "UP", # PyUpgrade
    "F",  # Pyflakes
    "E",  # Pycodestyle Errors
    "W",  # Pycodestyle Warnings
    "B",  # Flake8 Bugbear
    "SIM",# Flake8 Simplify
    "C4", # Flake8 Comprehensions
]