entity:
  id: example_entity
  name: Exmaple entity type
attribs:
  int_attr:
    name: Test attribute (int)
    description: An integer attribute for testing of DP3
    type: plain
    data_type: int
  string_attr:
    name: Test attribute (str) with history
    description: A string attribute for testing of DP3, this one stores history of previous values
    type: observations
    data_type: string
    history_params:
      max_age: 7d
