ipv4:
   entity:
      id: ipv4
      name: ipv4 address
      key_data_type: string
      auto_create_record: false
   attribs:
      attr1:
         name: attribute1
         data_type: tag
      attr2:
         name: attribute2
         data_type: string
asn:
   entity:
      id: asn
      name: autonomous system number
      key_data_type: int
      auto_create_record: false
   attribs:
      attr4:
         name: attribute4
         data_type: ipv4