ip:
   entity:
      id: ip
      name: ip address
      key_data_type: string
      auto_create_record: false
   attribs:
      attr1:
         data_type: tag
      attr2:
         data_type: string
      attr3:
         data_type: time
      attr4:
         data_type: float
      attr5:
         data_type: ipv4
      attr6:
         data_type: ipv6
      attr7:
         data_type: set<int>
asn:
   entity:
      id: asn
      name: autonomous system number
      key_data_type: int
      auto_create_record: false
   attribs:
      attr3:
         name: attribute4
         data_type: ipv4