# Configuration of HistoryManager system, responsible for deleting old
# datapoints

# Deleting old datapoints
datapoint_cleaning:
  # Tick rate - period in minutes for running the function
  tick_rate: 30
