# Configuration file for updater
#
# Updater periodically issues tasks to trigger regular updates of all entities in database
# Regular updates are configured separately for every entity type.
#
# Format:
# {entity_type}:
#   updater:
#     {interval_in_hours}: {name_of_event}
#     {interval_in_hours}: {name_of_event}
#   ttl_tokens:
#     {token_name}: {interval_in_hours}
#     {token_name}: {interval_in_hours}
# Example:
# ip:
#   updater:
#     1: "!every1h"
#     24: "!every1d"
#   ttl_tokens:
#     "default": 168