version: "3.4"
# This Compose file runs the worker and API from endpoints installed with the DP3 package.
# Useful for testing DP3 modules that are specific to the application and require no changes of DP3,
# or testing other smaller changes (attribute configuration changes etc.).

services:
  api:
    container_name: "{{DP3_APP}}_api"
    image: "__dp3_app___interpreter"
    build:
      context: .
      dockerfile: "docker/python/Dockerfile"
      target: "base"

    network_mode: "host"

    working_dir: "/dp3/dp3/api"
    environment:
      APP_NAME: "{{DP3_APP}}"
      CONF_DIR: "/dp3/config"
    command: ["api"]

  worker:
    container_name: "{{DP3_APP}}_worker"
    image: "__dp3_app___interpreter"
    build:
      context: .
      dockerfile: "docker/python/Dockerfile"
      target: "base"

    network_mode: "host"

    working_dir: "/dp3/"
    command: [ "worker", "{{DP3_APP}}", "config", "0", "-v" ]
